### PR TITLE
Do not hardcode version, just take it from r2

### PR DESCRIPTION
**Pull request by radare**
**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by wargio** [comment]
You refactored too much

**Comment by radare** [comment]
Last one is 4.3.1

**Comment by wargio** [comment]
there is no deb on the server

**Comment by radare** [comment]
still?

**Comment by wargio** [comment]
ok, now 4.3.1 are available. now it builds correcly

**Comment by radare** [comment]
Thanks

**Pull request merged**
